"""update_access_grant_schema

Revision ID: 8684d42d6e93
Revises: ca16cc670e90
Create Date: 2025-11-29 08:15:23.683863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8684d42d6e93'
down_revision: Union[str, None] = 'ca16cc670e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_grants', sa.Column('credits_total', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('access_grants', sa.Column('source_ref', sa.String(length=100), nullable=True))
    op.alter_column('access_grants', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('access_grants', 'grantor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('access_grants', 'grantee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('access_grants', 'expiry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('access_grants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('access_grants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_access_grants_grantee_id'), 'access_grants', ['grantee_id'], unique=False)
    # op.drop_column('access_grants', 'study_id') # Keep study_id
    op.drop_column('access_grants', 'credits_allocated')
    op.drop_column('access_grants', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_grants', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('access_grants', sa.Column('credits_allocated', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.add_column('access_grants', sa.Column('study_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True)) # Keep study_id
    op.drop_index(op.f('ix_access_grants_grantee_id'), table_name='access_grants')
    op.alter_column('access_grants', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('access_grants', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('access_grants', 'expiry_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('access_grants', 'grantee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('access_grants', 'grantor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('access_grants', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='id::text')
    op.drop_column('access_grants', 'source_ref')
    op.drop_column('access_grants', 'credits_total')
    # ### end Alembic commands ###
