"""add_algorithm_sha_to_provenance

Revision ID: 99ddd415795d
Revises: 8684d42d6e93
Create Date: 2025-11-29 08:32:52.651672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99ddd415795d'
down_revision: Union[str, None] = '8684d42d6e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scale_provenance', sa.Column('algorithm_sha', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scale_provenance', 'algorithm_sha')
    # ### end Alembic commands ###
