"""remove_store_tables

Revision ID: aca106f5b211
Revises: d9b2c3747197
Create Date: 2025-11-26 04:29:04.469469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'aca106f5b211'
down_revision: Union[str, None] = 'd9b2c3747197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS store_order_items CASCADE")
    op.execute("DROP TABLE IF EXISTS store_orders CASCADE")
    op.execute("DROP TABLE IF EXISTS store_products CASCADE")
    # Check if gamification_badges exists before dropping, or just drop it if we are sure
    # Since we are cleaning up, let's drop it.
    # Note: We need to handle the case where it might not exist if the previous migration didn't create it
    # But downgrade assumes it exists (referenced by FK).
    # Let's assume it exists.
    # op.drop_table('gamification_badges') 
    # Wait, downgrade does NOT create gamification_badges. 
    # This means it is NOT part of the "store" tables that were added in the previous revision?
    # Or maybe it was added way back.
    # If I want to remove it, I should add it here.
    # But if I don't have the create_table in downgrade, then downgrade will fail if I drop it here?
    # No, downgrade restores the state. If I drop it here, downgrade should CREATE it.
    # But downgrade currently does NOT create it.
    # So if I drop it here, I break downgrade (it won't be restored).
    # Unless I add create_table to downgrade too.
    
    # For now, I will only drop the tables that downgrade creates, to ensure symmetry.
    # If gamification_badges is left behind, it's a minor zombie.
    # But wait, store_products references it.
    # If I drop store_products, the FK is gone.
    # So gamification_badges can stay or go.
    # If I want to be thorough, I should drop it and add create to downgrade.
    # But I don't have the schema for gamification_badges handy to recreate it in downgrade.
    # So I will leave gamification_badges alone for now, or just drop the store tables.
    pass



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_responses_session_id', 'user_responses', ['session_id'], unique=False)
    op.create_index('ix_user_learning_styles_session', 'user_learning_styles', ['session_id'], unique=False)
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('ix_team_rollup_team_date', 'team_assessment_rollup', ['team_id', 'date'], unique=False)
    op.create_index('ix_scale_scores_session', 'scale_scores', ['session_id'], unique=False)
    op.create_index('ix_report_share_links_session_mediator', 'report_share_links', ['session_id', 'mediator_id'], unique=False)
    op.create_index('ix_report_share_links_owner', 'report_share_links', ['owner_id'], unique=False)
    op.create_index('ix_percentile_scores_session', 'percentile_scores', ['session_id'], unique=False)
    op.create_index('ix_normative_conv_group_ver_scale_raw', 'normative_conversion_table', ['norm_group', 'norm_version', 'scale_name', 'raw_score'], unique=False)
    op.create_index('ix_lfi_context_scores_session_context', 'lfi_context_scores', ['session_id', 'context_name'], unique=False)
    op.create_index('ix_item_choices_item', 'item_choices', ['item_id'], unique=False)
    op.create_index('ix_combination_scores_session', 'combination_scores', ['session_id'], unique=False)
    op.create_index('ix_backup_learning_styles_session', 'backup_learning_styles', ['session_id'], unique=False)
    op.drop_index(op.f('ix_assessment_sessions_guest_token'), table_name='assessment_sessions')
    op.alter_column('assessment_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('assessment_sessions', 'guest_token')
    op.create_index('ix_assessment_items_number_type', 'assessment_items', ['item_number', 'item_type'], unique=False)
    op.create_index('ix_assessment_items_item_type', 'assessment_items', ['item_type'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('base_price', sa.INTEGER(), nullable=False),
    sa.Column('required_badge_id', sa.INTEGER(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['required_badge_id'], ['gamification_badges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_products_slug', 'store_products', ['slug'], unique=True)
    op.create_table('store_order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price_at_purchase', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['store_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_order_items_product', 'store_order_items', ['product_id'], unique=False)
    op.create_index('ix_store_order_items_order', 'store_order_items', ['order_id'], unique=False)
    op.create_table('store_orders',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.INTEGER(), nullable=False),
    sa.Column('contribution_points', sa.INTEGER(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('snap_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_orders_user_id', 'store_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###
