"""add_study_id_to_grants

Revision ID: ca16cc670e90
Revises: aca106f5b211
Create Date: 2025-11-27 23:18:41.605151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ca16cc670e90'
down_revision: Union[str, None] = 'aca106f5b211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_assessment_sessions')
    # op.add_column('access_grants', sa.Column('study_id', sa.String(length=50), nullable=True, comment='External Research Study ID for provenance'))
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_assessment_sessions_guest_token'), ['guest_token'], unique=False)
    op.drop_index('ix_backup_learning_styles_session', table_name='backup_learning_styles')
    op.drop_index('ix_combination_scores_session', table_name='combination_scores')
    op.drop_index('ix_item_choices_item', table_name='item_choices')
    op.drop_index('ix_lfi_context_scores_session_context', table_name='lfi_context_scores')
    op.drop_index('ix_normative_conv_group_ver_scale_raw', table_name='normative_conversion_table')
    op.drop_index('ix_percentile_scores_session', table_name='percentile_scores')
    op.drop_index('ix_report_share_links_owner', table_name='report_share_links')
    op.drop_index('ix_report_share_links_session_mediator', table_name='report_share_links')
    op.drop_index('ix_scale_scores_session', table_name='scale_scores')
    op.drop_index('ix_team_rollup_team_date', table_name='team_assessment_rollup')
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_index('ix_user_learning_styles_session', table_name='user_learning_styles')
    op.drop_index('ix_user_responses_session_id', table_name='user_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_responses_session_id', 'user_responses', ['session_id'], unique=False)
    op.create_index('ix_user_learning_styles_session', 'user_learning_styles', ['session_id'], unique=False)
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('ix_team_rollup_team_date', 'team_assessment_rollup', ['team_id', 'date'], unique=False)
    op.create_index('ix_scale_scores_session', 'scale_scores', ['session_id'], unique=False)
    op.create_index('ix_report_share_links_session_mediator', 'report_share_links', ['session_id', 'mediator_id'], unique=False)
    op.create_index('ix_report_share_links_owner', 'report_share_links', ['owner_id'], unique=False)
    op.create_index('ix_percentile_scores_session', 'percentile_scores', ['session_id'], unique=False)
    op.create_index('ix_normative_conv_group_ver_scale_raw', 'normative_conversion_table', ['norm_group', 'norm_version', 'scale_name', 'raw_score'], unique=False)
    op.create_index('ix_lfi_context_scores_session_context', 'lfi_context_scores', ['session_id', 'context_name'], unique=False)
    op.create_index('ix_item_choices_item', 'item_choices', ['item_id'], unique=False)
    op.create_index('ix_combination_scores_session', 'combination_scores', ['session_id'], unique=False)
    op.create_index('ix_backup_learning_styles_session', 'backup_learning_styles', ['session_id'], unique=False)
    op.drop_index(op.f('ix_assessment_sessions_guest_token'), table_name='assessment_sessions')
    op.alter_column('assessment_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('access_grants', 'study_id')
    op.create_table('_alembic_tmp_assessment_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('assessment_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('assessment_version', sa.VARCHAR(length=10), nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), nullable=True),
    sa.Column('strategy_code', sa.VARCHAR(length=40), nullable=True),
    sa.Column('pipeline_version', sa.VARCHAR(length=40), nullable=True),
    sa.Column('session_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('days_since_last_session', sa.INTEGER(), nullable=True),
    sa.Column('is_finalized', sa.BOOLEAN(), nullable=False),
    sa.Column('results_json', sqlite.JSON(), nullable=True),
    sa.Column('guest_token', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
