"""init_access_grants

Revision ID: d9b2c3747197
Revises: 0027_store_order_contributions
Create Date: 2025-11-25 15:26:45.151202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b2c3747197'
down_revision: Union[str, None] = '0027_store_order_contributions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('grantor_id', sa.Integer(), nullable=False),
    sa.Column('grantee_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('credits_allocated', sa.Integer(), nullable=False),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grantee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grantor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['store_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_grants')
    # ### end Alembic commands ###
